services:
  nodo1:
    build: ./nodo1-clientes
    ports: ["8080:80"]
    networks: [red_publica]
    depends_on: [nodo2]
  nodo2:
    build:
      context: .
      dockerfile: nodo2-backend/Dockerfile
    env_file: .env
    environment:
      ICE_NODO3_HOST: nodo3
      DB_HOST: ${DB_HOST:-host.docker.internal}
    extra_hosts: ["host.docker.internal:host-gateway"]
    networks: [red_publica, red_pagos]
    # Nodo 2 espera PostgreSQL con reintentos propios.
  nodo3:
    build:
      context: .
      dockerfile: nodo3-pasarelas/Dockerfile
    environment:
      ICE_CALLBACK_HOST: nodo2
      ICE_CALLBACK_PORT: 10001
      ICE_NODO3_PORT: 10000
      SECRETO_FIRMA_SIMULACION: ${SECRETO_FIRMA_SIMULACION:-desarrollo-apexstore-no-usar-en-produccion}
    networks: [red_pagos]
networks:
  red_publica: {}
  red_pagos:
    internal: true
