plugins { id 'application' }
dependencies {
 implementation project(':contratos'); implementation project(':contratos-ice'); implementation 'com.zeroc:ice:3.7.10'
 implementation 'com.zaxxer:HikariCP:6.2.1'; implementation 'org.postgresql:postgresql:42.7.5'
 implementation 'org.flywaydb:flyway-core:11.3.4'; implementation 'org.flywaydb:flyway-database-postgresql:11.3.4'
 implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'; implementation 'org.slf4j:slf4j-api:2.0.16'; runtimeOnly 'ch.qos.logback:logback-classic:1.5.16'
}
application { mainClass = 'com.apexstore.nodo2.InicializadorBaseDatos' }
tasks.named('run', JavaExec) { workingDir rootProject.projectDir }
